prometheus/client_ruby

- lib/prometheus/client/formats/text.rb
- spec/prometheus/client/formats/text_spec.rb
@grobie: as per the [exposition format spec](https://docs.google.com/document/d/1ZjyKiKxZV83VI9ZKAXRGKaUKK2BIWCT7oiGBKDBpjEY/edit#), summaries exposed in text format should use the suffix `_count` instead of `_total`:
> The type summary is difficult to represent in the text format. The following conventions apply:
>   - Each quantile x is given as a separate sample, each with a label {quantile="_x_"}.
>   - The sample sum for a summary named x is given as a separate sample named _x\_sum_.
>   - The sample count for a summary named x is given as a separate sample named _x\_count_.
> Use `_count` instead of `_total` when exposing summaries

- lib/prometheus/client/rack/collector.rb
- spec/prometheus/client/rack/collector_spec.rb
Some apps are serving multiple domains, this is quite useful for that case.
> Add host to Collector

- lib/prometheus/client/rack/collector.rb
- spec/examples/metric_example.rb
- spec/prometheus/client/formats/text_spec.rb
- spec/prometheus/client/rack/collector_spec.rb
I recently used prometheus to monitor web servers in go and ruby/rake that are using the official prometheus client libraries.  I noticed that the go and ruby/rake client libs were using different names for the http metrics:
* go: http_request_duration_microseconds
* ruby/rake: http_request_durations_microseconds
I assumed that the prometheus clients should be using the same metric names.
> Change http_request metric names to match go

- lib/prometheus/client/counter.rb
- spec/prometheus/client/counter_spec.rb
It was decided that counters should always be monotonically increasing,
so we have to remove possibilities to decrement a counter.
Fixes #16.
@jc @juliusv
> Remove Counter#decrement

- lib/prometheus/client/formats/text.rb
- lib/prometheus/client/histogram.rb
- lib/prometheus/client/registry.rb
- spec/prometheus/client/formats/text_spec.rb
- spec/prometheus/client/histogram_spec.rb
- spec/prometheus/client/registry_spec.rb
> histogram support for ruby client

- examples/rack/run
Run script throws a `/run: line 38: syntax error near unexpected token >` on OSX
> Issue in example run script

- lib/prometheus/client/metric.rb
Tiny improvement on objects allocations
> Remove extra Proc allocation from metrics sync.

- examples/rack/README.md
@RichiH So I can just point users to that example in the future.
> Use path normalization in collect label builder example

- lib/prometheus/middleware/collector.rb
Quite a few people run into the issue of creating too many time series
by exporting an unbounded number of paths label values. While it's
documented and possible to provide a custom label builder, a better
default is probably to always normalize ids in HTTP paths.
@SuperQ @brian-brazil
> Normalize paths including numeric IDs by default

- README.md
- lib/prometheus/client/gauge.rb
- spec/prometheus/client/gauge_spec.rb
Currently, gauges are hard to use as bi-directional counters due to a lack of increment and decrement operations on them.
So I've found myself writing following scary fragments of the code:
```ruby
simultaneous_service_calls_gauge.send(:synchronize) do
value = simultaneous_service_calls_gauge.get(tags) || 0
simultaneous_service_calls_gauge.set(tags, value + 1)
end
simultaneous_service_calls_gauge.send(:synchronize) do
value = simultaneous_service_calls_gauge.get(tags) || 0
simultaneous_service_calls_gauge.set(tags, value - 1)
end
```
That's why this PR exists:
```rb
simultaneous_service_calls_gauge.increment(tags)
simultaneous_service_calls_gauge.increment(tags)
```
For now, I've made `increment` and `decrement` to initialize values with `0` before changing (default value of gauge is …
> Add thread safe increment and decrement operations to gauges

- lib/prometheus/middleware/collector.rb
- spec/prometheus/middleware/collector_spec.rb
It can sometimes be handy to expose the HTTP server metrics under a
different prefix, either for naming consistency (so all your app metrics
have a common prefix), or to prevent conflicts (it is possible, and
occasionally useful, to run more than one Rack-based webserver in a single
process, although it can be a bit of a wrestle).
Includes tests, which pass on at least 2.3 (things seem spectacularly broken on at least 1.9 and 2.0, for unrelated reasons) and doesn't introduce any new rubocop sadnesses.
> Support Collector middleware using custom metric names

- .rubocop.yml
- lib/prometheus/middleware/collector.rb
- spec/prometheus/middleware/collector_spec.rb
Hello!
We have a lot of microservices written in ruby, and in our ecosystem (which handles tons of transactions every day) we are using UUID's for our entities. Unfortunately, the Ruby client for Prometheus does not by default normalize UUIDs which required us to get closer to the source code of this gem.
One could argue that this should not be core default behaviour of the gem and that as users we should use the option parameter for `counter_label_builder` and `duration_label_builder` instead. We did that, but it is quite a bother going into each microservice and spreading these local overrides. That's why we put it in a forked version of the client, but ideally we would like it to be part of the library itself.
One last thing to consider, do you believe that UUIDs are growing popular in …
> Normalize UUIDs in request path by default

- README.md
A counter in Prometheus can not go down and should not have the _total
suffix.
@brian-brazil That slipped through somehow.
> Improve gauge documentation example

- README.md
- examples/rack/config.ru
In newer rack versions the if guard fails with a missing method for
`.any?`. The quickest fix is to remove the guard.
> Updated Rack configuration

- lib/prometheus/client/label_set_validator.rb
- spec/prometheus/client/label_set_validator_spec.rb
I'm new to the whole Prometheus concepts and I often struggle with this error tinkering with labels and base_labels and so on. Testing in irb/pry usually works fine but running a more complex code with "dynamic" labels is somewhat hard to debug, so I made this minor change to help spotting the problem.
@grobie
EDITH: travis failure unrelated to this PR. Coverage decreased due to multiline error message. Should I put this in a single line ? (wasn't sure about your line-length policy)
> Extend the invalid signature message

- README.md
- Don't suggest defining metrics outside of file they're used in
- Don't allow stores to require extra parameters in `for_metric`
- Correct note on kernel page cache
Fixes #113, Fixes #114
> Make suggested tweaks to README from feedback in #95

- lib/prometheus/middleware/collector.rb
- spec/prometheus/middleware/collector_spec.rb
We decided in #111 that the current interface for this is confusing to
the point where it's more trouble than it's worth.
The alternatives we came up with result in the middleware doing almost
nothing and delegating to user-provided lambdas.
Since we're pre-1.0, we're removing this in the belief that if it turns
out to be a widely-requested feature, we can come up with something
better. Leaving this implementation in would commit us to an interface
we don't like.
Fixes #111
> Remove support for flexible labels in collector middleware

- lib/prometheus/client/version.rb
This prepares us to cut our first alpha release with multi-process
support, as requested in #95.
Fixes #95. Will cut the new release tomorrow.
> Bump version to 0.10.0-alpha.1

- README.md
- lib/prometheus/client/data_stores/direct_file_store.rb
- lib/prometheus/client/label_set_validator.rb
- spec/prometheus/client/data_stores/direct_file_store_spec.rb
- spec/prometheus/client/label_set_validator_spec.rb
This is the beginning of the work for #107. I'm going to detail the plan I came up with in there.
Not mega happy with this implementation, so I've marked this PR as a draft for now. Will see if I can come up with anything better.
> Support :all as an aggregation mode in DirectFileStore

- lib/prometheus/client/data_stores/direct_file_store.rb
- spec/prometheus/client/data_stores/direct_file_store_spec.rb
This changes `DirectFileStore` to use the `:all` aggregation mode for gauges by default.
I'm considering adding a config option to the store to allow the default to be overridden, for use in cases where people want to provide their own label that distinguishes between processes but changes less often than process IDs do.
I'll try to add a commit early next week for that.
Fixes #107
> Export per-pid values from gauges by default

- lib/prometheus/client/registry.rb
This PR fixes a bug in the registry that prevented the user from configuring the store settings of new metrics.
cc @dmagliola @Sinjo
> Fixes bug that prevented store settings from being passed to the metrics

- lib/prometheus/client/data_stores/direct_file_store.rb
- lib/prometheus/client/data_stores/single_threaded.rb
- lib/prometheus/client/data_stores/synchronized.rb
- prometheus-client.gemspec
- spec/benchmarks/data_stores.rb
We added this dependency to be able to use `ReadWriteLock`, which is
a reentract lock. We did not need the Read/Write locking distinction,
and at the time, we didn't know that `Monitor` was reentrant, so this
seemed to be the best solution.
Knowing that `Monitor` is reentrant, we can get rid of the dependency,
and simply use `Monitor` instead.
Note that we keep `concurrent-ruby` as a *dev* dependency, because the
performance benchmarks use other primitives provided by it to synvhronize
their threads, but it's not needed for specs to pass, or for production use.
As an added bonus, this appears to be measurably faster on multiple thread scenarios.
I only ran a quick benchmark on my laptop, so this is to be taken with a grain of salt,
but at least it doesn't seem to be worse.
> Remove `concurrent-ruby` dependency

- COMPATIBILITY.md
Create a starting compatibility guide that can help maintainers support
the on-going development of this client.
> COMPATIBILITY.md

- lib/prometheus/client/label_set_validator.rb
- spec/prometheus/client/histogram_spec.rb
- spec/prometheus/client/label_set_validator_spec.rb
- spec/prometheus/client/summary_spec.rb
This PR fixes the race condition reported in PR #70 
Fixing that alone, by removing the cache, makes the validation quite a bit slower. However, these 2 changes together make it *much* faster, and both of these changes together have a much bigger performance effect than each in isolation, so i'm bundling them up:
---------------------------------------------
Currently, when we validate a labelset on increment, we cache that we've seen this particular labelset, so we can avoid revalidating it next time we see it.
This is currently not thread-safe, since we're not synchronizing access to the hash we use for that cache. This is only a problem in non-MRI, but we are supporting those.
Removing this cache has a slight performance hit for metrics with labels, but removing the cache, in …
> Stop caching validated Labelsets, and improve Validation performance

- lib/prometheus/client/metric.rb
- spec/examples/metric_example.rb
- spec/prometheus/client/counter_spec.rb
- spec/prometheus/client/gauge_spec.rb
- spec/prometheus/client/histogram_spec.rb
- spec/prometheus/client/summary_spec.rb
Currently, you get an inconsistent experience when using different store
implementations (e.g. `SingleThreaded` vs `DirectFileStore`).
Because `DirectFileStore` has to write your metrics into a file, it
has to convert label values into strings. That means that when you
access them they're strings. Other stores don't do this, so you can
access them as symbols if you provided them as symbols.
To give users a consistent experience when swapping between stores, this
commit changes the Metric base class to convert the label values to
strings before they get anywhere near the underlying store.
current master:
```
0 labels      3.732M (± 1.9%) i/s -     18.662M in   5.003057s
2 labels      1.008M (± 2.4%) i/s -      5.039M in   5.000649s
100 labels     31.093k (± 2.2%) i/s -    156.208k in …
```
>  Convert label values to strings in base Metric class

- lib/prometheus/client/data_stores/direct_file_store.rb
- spec/examples/data_store_example.rb
Up to now, we've had some subtle behavioural differences between stores;
one of which was that stores weren't consistent about what they returned
for label sets that hadn't been initialised.
This commit adds some shared examples that enforce consistent behaviour
between the stores and fixes DirectFileStore to follow that behaviour.
> Test that stores return floats and fix DirectFileStore to do so

- lib/prometheus/client/data_stores/direct_file_store.rb
- spec/prometheus/client/data_stores/direct_file_store_spec.rb
Currently, if you fork after altering a metric value when using
DirectFileStore, the child process will have a handle to the original
process's metric store.
This commit detects checks for that condition on any instrumentation
event and opens a new metric file for the new PID.
Fixes #119
> Reopen files in DirectFileStore when the process has forked

- Gemfile
Little bit of cleanup I thought I'd do since I spotted it.
Only impacts test dependencies anyway.
> Remove dependency pins for unsupported Ruby versions

- lib/prometheus/client/version.rb
What we've got now is pretty damn stable.
We've got stuff in the backlog, but there's no reason to delay promoting our current release from alpha to something proper.
Doing this has the nice property of our `README` lining up  with the library you get from `gem install`, which doesn't give you the alpha version unless you ask for it.
@dmagliola As we discussed at work. I'll follow up with the docs PR(s) - no need for them to coincide with a release! We can have a crack at the more interesting ones when I'm back if you fancy.
> Bump version to 0.10.0

- lib/prometheus/client/data_stores/direct_file_store.rb
(This patch is adapted from https://github.com/gocardless/prometheus_client_ruby/pull/5) 
During the read path (metrics export) we open all existing metric files
and read through them in order to aggregate metrics across different
processes. When reading non-empty files we end up parsing file content
twice: first during FileMappedDict initialisation, then again in the
caller site (`all_values`).
This commit refactors FileMappedDict so that while the `@positions` map
is populated at creation time, the actual metric values are read only
when explicitly requested. This avoids the memory bloat of unpacking
file content twice.
---
The attached synthetic benchmark simulates two concurrent threads that
write and read from a shared direct_file_store while memory profiling
is enabled. I observed …
> Reduce memory bloating in FileMappedDict when reading metrics.

- README.md
As of 0.9.0 (and in particular #102) Björn has made the warning of the legacy API no longer accurate.  Let's update the README too.
> readme: remove warning of legacy pushgateway API

- lib/prometheus/middleware/collector.rb
Also describe `:metrics_prefix` option.
PTAL @Sinjo.
> Remove outdated doc from collector middleware

- lib/prometheus/client/data_stores/direct_file_store.rb
- spec/prometheus/client/data_stores/direct_file_store_spec.rb
In the DirectFileStore, in order to store the labels hash on disk, we
turn it into a "querystring". The way this is done, we'll end up with
different strings if the same hash is passed in with its keys in
different order.
Since this string is used to index into the file where we store the data,
this will lead to two different values being stored for the same hash.
This is fine in cases where the aggregation is :SUM, because they end up
getting summed when the Client is summarizing. But in :ALL aggregation,
for example, you will end up with one value or the other, randomly.
The test in this commit reproduces this problem.
This way of serializing the labels is a bit slower,
but it's not a huge impact in the big scheme of things, and it leads to
the correct result. …
> Fix bug where different label orders lead to different results

- README.md
- lib/prometheus/client/data_stores/direct_file_store.rb
The main changes are documenting some important caveats that are relevant
when running DirectFileStore in production, and the `ALL` aggregation
method for Gauges
> Improve documentation for DirectFileStore

- lib/prometheus/client/version.rb
After almost a year with this code in production, all our backward
incompatible changes addressed, and much improved documentation,
we are now in a good place to call this "ready for everyone to use"
> Release v1.0 🎉

- README.md
- lib/prometheus/client/histogram.rb
- lib/prometheus/client/metric.rb
- lib/prometheus/client/summary.rb
- spec/prometheus/client/counter_spec.rb
- spec/prometheus/client/gauge_spec.rb
- spec/prometheus/client/histogram_spec.rb
- spec/prometheus/client/summary_spec.rb
This a draft PR of a solution for the problem described in #141.
> Implements #init_label_set method for all metric classes

- lib/prometheus/client/data_stores/README.md
The target is findable but I thought this might help others down the road.
> fixes broken link to gocardless experiments

- examples/rack/README.md
This PR replaces the pre-2.0 style flag prefix (single dash) with the current double-dash flag prefix for the prometheus command in examples/rack/README.md
@dmagliola
> Change prometheus command to use double-dash for flags

- README.md
Attn: @dmagliola
Previously there was no mention of actually installing the gem, which is usually useful for a lot of more junior devs.
This PR just adds a few general lines making the name of the gem `prometheus-client` explicit and giving Gemfile and global installation examples.
Signed-off-by: Christopher Guess <cguess@gmail.com>
> Add Gem & Bundler instructions to README

- lib/prometheus/client/histogram.rb
- spec/prometheus/client/histogram_spec.rb
whose value is the same as the observed value
Seems to be working  in v0.9.0 
https://github.com/prometheus/client_ruby/blob/9bae72520e7fdadab983ddd2cd40832e37489793/lib/prometheus/client/histogram.rb#L29
which behavior is correct?
> observed value should be stored the bucket

- README.md
Add an example on how to solve the "files are already there on
startup" problem, based on @stefansundin 's proposal in PR #173
> Document how to clean up work dir for DirectFileStore on startup

- README.md
- lib/prometheus/client/histogram.rb
- spec/prometheus/client/histogram_spec.rb
Most client libraries provide helpers for generating linear/exponential
histogram buckets. This provides the same interface as the golang
client.
> Histogram bucket helpers

- .travis.yml
2.3 and 2.4 are EOL now, and 2.7 officially exists
> Support Latest Ruby versions

- README.md
- lib/prometheus/client/data_stores/direct_file_store.rb
- spec/prometheus/client/data_stores/direct_file_store_spec.rb
Add `:most_recent` aggregation to DirectFileStore, which reports the value that was set by a process most recently.
I am using this for a small app called github-activity, and it tracks the remaining GitHub ratelimit using Prometheus (this is the only metric at the moment). The existing aggregations didn't really fit my use case, since for this use case, the last reported value from GitHub is the one that I care about. So I decided to try to improve the gem to support my use case, and I came up with this.
Please let me know about nitpicks and other things. I wasn't sure what the best name would be for this aggregation, and I was basically picking between `:latest` and `:most_recent`. And I am unsure if this should be using `CLOCK_MONOTONIC` or if `Time.now.to_f` is Ok.
Thanks!
Useful …
> Add :most_recent aggregation to DirectFileStore

- .rspec
- spec/spec_helper.rb
We were running our tests with warnings off, which meant we didn't notice
a bunch of warnings we were emitting.
> Turn on Ruby Warnings on Test Suite

- lib/prometheus/client/data_stores/direct_file_store.rb
- lib/prometheus/client/histogram.rb
- lib/prometheus/client/metric.rb
- lib/prometheus/client/summary.rb
Our tests are running without outputting warnings, so we don't see a number
of things Ruby was warning us about.
All these code changes are effectively a NOOP.
> Fix Ruby Warnings

- lib/prometheus/client/push.rb
- spec/prometheus/client/push_spec.rb
This method has been deprecated for a while, and it gives us warnings in Ruby 2.7
> Remove call to deprecated `URI.escape`

- lib/prometheus/client/registry.rb
- spec/prometheus/client/registry_spec.rb
The registry is backed by a Hash, which is not guaranteed to be thread
safe on all interpreters. For peace of mind, this change synchronizes
all accesses to the metrics hash.
Another option would have been to use a [thread-safe Hash][1] instead of
a Hash but this would have meant adding Ruby Concurrent as a
dependency, which I'm assuming we don't want.
Ref: https://github.com/prometheus/client_ruby/pull/184#discussion_r406038191
[1]: https://github.com/ruby-concurrency/concurrent-ruby/blob/v1.1.7/lib/concurrent-ruby/concurrent/hash.rb
> Make all registry methods thread safe

- lib/prometheus/middleware/collector.rb
- spec/prometheus/middleware/collector_spec.rb
When determining the path for a request, `Rack::Request` prefixes the
`SCRIPT_NAME`, [as seen here][1].
This is a problem with our current code when using mountable engines,
where the engine part of the path gets lost.
This patch fixes that to include `SCRIPT_NAME` as part of the path.
NOTE: This is not backwards compatible. Labels will change in existing
metrics. We will cut a new major version once we ship this.
[1]: https://github.com/rack/rack/blob/294fd239a71aab805877790f0a92ee3c72e67d79/lib/rack/request.rb#L512
> Include SCRIPT_NAME when determining path in Collector

- lib/prometheus/middleware/exporter.rb
- spec/prometheus/middleware/exporter_spec.rb
If the port option is set, all requests for /metrics on other ports will be forwarded to the app. If it is unset or nil, or the ports match, export things as usual.
Allows separate mounting of metrics and main app to enforce different security setups etc.
> Add port option to exporter middleware

- README.md
I've followed the documentation in order to setup prometheus client with Rails.
The use of `::Prometheus::Client::DataStores::DirectFileStore` was very clear. However, it was unexpected for me to have the list of the metrics stored in memory.
When testing locally, I've got empty result from `/metrics` because the metrics were defined in another process that the endpoint.
Definition of metrics after fork can lead to random inconsistencies. That's why I propose to alert on this behavior.
Signed-off-by: Emmanuel Delmas <emmanuel.delmas@jobteaser.com>
> Document metrics definition behavior with fork

- MAINTAINERS.md
I'm pretty much only working on this outside of work now, so it makes more sense to use the same email address that I use for everything else related to open source.
> Update email address in MAINTAINERS.md

- lib/prometheus/client/metric.rb
- spec/prometheus/client/counter_spec.rb
- spec/prometheus/client/gauge_spec.rb
- spec/prometheus/client/histogram_spec.rb
- spec/prometheus/client/summary_spec.rb
Issue #208 
According to [Prometheus Best Practices](https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics), client libraries are expected to automatically export a 0 value when declaring a metric that has no labels.
We missed this so far in the Ruby client, this PR rectifies that.
NOTE: This can be considered a breaking change. On the one hand, it's a bug fix, but on the other, it will make many time series materialize when scraping apps that use the client, that previously wouldn't have.
Depending on how many label-less metrics the app is declaring, this may have a significant impact, so we should probably cut a new major version and warn about this in the Release Notes.
> Automatically initialize time series without labels

- lib/prometheus/client/push.rb
Fixes #202
Tested the fix on 2.7.2 with the push gateway running locally and it seems to do the trick:
```
sinjo@coin:~/projects/client_ruby$ bx irb
irb(main):001:0> require "prometheus/client/push"
=> true
irb(main):002:0> registry = Prometheus::Client.registry
=> #<Prometheus::Client::Registry:0x00005620d98717e8 @metrics={}, @mutex=#<Thread::Mutex:0x00005620d9871658>>
irb(main):003:0> Prometheus::Client::Push.new('test-job').add(registry)
=> #<Net::HTTPOK 200 OK readbody=true>
```
> Add missing 'cgi' require in push client

- lib/prometheus/client/push.rb
- spec/prometheus/client/push_spec.rb
👋 !
We recently had an issue in our infrastructure where a Push Gateway was getting overloaded due to too much metric cardinality in the time series data that we were sending. We remedied this issue and things are well, but part of the way we noticed was that these pushes were happening in our job workers, which we have a lot of timing instrumentation around.
Digging in a bit further, we noticed that a huge number jobs were taking 60 seconds to complete, when they are normally much (sub-second) faster. We realized that this was due to our calls out to the push gateway, which would eventually time out. We wanted to be able to set the push timeout to be significantly lower (1-5 seconds) so that we can fail fast and avoid eating into our job capacity if there is ever an issue with our …
> Enable configuring `Net::HTTP` timeouts

- lib/prometheus/client/push.rb
- spec/prometheus/client/push_spec.rb
This implements some of the changes from #186. This is an intermediate PR to avoid building up too many unmerged commits.
> Improve path handling in pushgateway client

- COMPATIBILITY.md
We switched from Travis to CircleCI, so this needs to point at a different file now.
> Fix link to build matrix in COMPATIBILITY.md

- .circleci/config.yml
Ruby 2.5 dropped out of support at the end of March 2021, and Ruby 3.1 was released on Christmas Day.
> Update Ruby versions used in CircleCI

- lib/prometheus/client/metric.rb
- lib/prometheus/client/push.rb
- spec/prometheus/client/push_spec.rb
This PR implements the remaining improvements from #186 that weren't in #220.
> Finish improvements to push client

- lib/prometheus/client/label_set_validator.rb
- spec/prometheus/client/label_set_validator_spec.rb
Up to now, we've only been performing limited validation of label names.
This commit validates that the characters use match the regex
`/\A[a-zA-Z_][a-zA-Z0-9_]*\Z/` as specified by:
https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels
---
I ran into this while working on #234 for #186, but thought I'd separate it out into its own PR.
It's technically a breaking change, but I can't imagine Prometheus would have been happy scraping labels with these names to begin with. On top of that, our master branch already has breaking changes on it for the 3.0 release, so I figure one more doesn't hurt.
> Validate label names

- lib/prometheus/client/push.rb
- spec/prometheus/client/push_spec.rb
While URLs do support passing Basic Auth credentials using the
`http://user:password@example.com/` syntax, the username and password in
that syntax have to follow the usual rules for URL encoding of
characters per RFC 3986
(https://datatracker.ietf.org/doc/html/rfc3986#section-2.1).
Rather than place the burden of correctly performing that encoding on
users of this gem, we decided to have a separate method for supplying
Basic Auth credentials, with no requirement to URL encode the characters
in them.
---
Since the tests around HTTP requests are extremely heavily mocked, I tested this locally with a real pushgateway configured with one user with `@` in the password and another with `:` in it, as well as a more boring password that only used basic latin alphabet characters. All three …
> Move to explicit method call for Basic Auth credentials in push client

- lib/prometheus/client/histogram.rb
- lib/prometheus/client/metric.rb
- spec/prometheus/client/counter_spec.rb
- spec/prometheus/client/gauge_spec.rb
- spec/prometheus/client/histogram_spec.rb
- spec/prometheus/client/summary_spec.rb
When calling `with_labels` on a metric object (let's call it "the original"), we instantiate a new metric (the "clone") that is identical except that it has some more pre-set labels, that allow the caller to observe it without having to specify the labels every time.
"currying", if you will.
The problem with the existing code (as exemplified by issue #225), is that as part of making this new metric, we end up instantiating a new store for this metric.
With in-memory stores, the new one will be empty. With file stores, it'll bring over the data from the original metric until the 
gets observed once, at which point they fork, while pointing at the same file and keeping separate internal state. An almost sure recipe for file corruption.
And when exporting, only the data in the "original" …
> Fix `with labels` bug reported in issue #225

- Gemfile
- README.md
- spec/spec_helper.rb
We've been having errors in CI from Coveralls, when trying to upload results.
(As mentioned in [this comment](https://github.com/prometheus/client_ruby/pull/230#issuecomment-864561231))
This error seems to be because our coveralls gem is pretty old and abandoned,
and probably using a TLS version that is no longer supported.
(Reference: https://github.com/lemurheavy/coveralls-ruby/issues/163)
One option recommended in that issue is to switch to a different `coveralls-ruby-reborn` gem.
However, given that we only use `coveralls` to upload results to the cloud,
only so we can have a badge in our README reporting 100%, in the interest of
security, I think i'd rather get rid of `coveralls` altogether, and use
`simplecov` directly instead, which reports the coverage when running the
tests and …
> Replace Coveralls with SimpleCov

- README.md
- UPGRADING.md
- lib/prometheus/client/push.rb
We've made a bunch of breaking changes recently, which will be part of
the 3.0.0 release. This commit updates our README to match the new API
in anticipation of that relese.
---
Fixes #240
> Update README.md and UPGRADING.md for 3.0.0 release

- UPGRADING.md
- lib/prometheus/middleware/collector.rb
- spec/prometheus/middleware/collector_spec.rb
> Use framework-specific route info and handle consecutive path segments containing IDs in Collector

- CHANGELOG.md
- lib/prometheus/client/version.rb
@dmagliola I've pulled in your work from #228, which we were going to use to cut an interim 2.2.0 release, and combined it all into one big section for the 3.0.0 release which we decided to go with instead.
Fixes #241
> Update CHANGELOG.md and gem version for 3.0.0 release

- prometheus-client.gemspec
Previously, we had the license name set to "Apache 2.0", which doesn't
conform to the entry in the list that `gem` validates against
(https://spdx.org/licenses/).
This commit replaces the space with a hyphen so that we match the format
expected by `gem`, and don't get this warning when we build the gem:
> WARNING:  license value 'Apache 2.0' is invalid.  Use a license
> identifier from http://spdx.org/licenses or 'Nonstandard' for a
> nonstandard license. Did you mean 'Apache-2.0'?
> Fix license name in gemspec

- CHANGELOG.md
- README.md
Other parts of the Prometheus project (namely the Prometheus server repo
itself, which sets a lot of norms for everything else) have already
adopted this rename, so we should follow suit.
This commit will need to be merged in tandem with a main branch name
change on GitHub, and possibly some reconfiguration in the repo settings
in CircleCI.
> Replace references to `master` branch with `main`

- prometheus-client.gemspec
This includes the LICENSE source in the built and released gem and further allows downstream packaging (e.g. RPM / deb) to include the official license file in the distributed source.
> Include LICENSE in gem

- .circleci/config.yml
I don't really follow JRuby any more, so this release passed me by, but
I figure it's worth adding to our build matrix.
> Add JRuby 9.3 to the build matrix

- examples/rack/config.ru
Because HTTP/2 requires that headers are sent in lowercase, Rack has started validating that no header contains an uppercase letter.
We were setting uppercase headers as that was a common convention in HTTP/1.1, where they were interpreted in a case-insensitive fashion.
This change makes us compatible with Rack 3.0 without breaking compatibiility for older versions (not that it would matter for this example code).
---
Fixes #267
> Use lowercase response headers in Rack example

- README.md
- lib/prometheus/middleware/exporter.rb
- spec/prometheus/middleware/collector_spec.rb
- spec/prometheus/middleware/exporter_spec.rb
Given Rack is validating HTTP headers has no uppercased letters, as mentioned in this previous PR https://github.com/prometheus/client_ruby/pull/268, the exporter needs to use lowercased letters to keep compatibility.
> Using lowercase for HTTP headers to make it compatible with HTTP/2 and Rack v3

- README.md
- examples/rack/README.md
- examples/rack/prometheus.yml
- examples/rack/run
- examples/rack/unicorn.conf
The example seems to be broken for some time. Here are the list of things fixed:
> Rack run example fixed

- .circleci/config.yml
A new version of `rubygems-update` was just released, which drops support for Ruby versions below 2.6.0. These older versions of JRuby target Ruby language versions earlier than that, so have been failing their CI runs.
This should get us back to green builds, and will be easy to remove once we drop support for the JRuby versions involved.
> Fix builds for JRuby <=9.2 in CircleCI

- .circleci/config.yml
Ruby 3.2 was released today, and I would truly hate for us to waste another second in adding it to our list of supported versions.
Happy Christmas everyone! 💖 
---
We may, however, have to wait on CircleCI to publish a 3.2 image 😅
> Add Ruby 3.2 to CI matrix

- lib/prometheus/client/data_stores/direct_file_store.rb
* Introduce `FileMappedDict#increment_value`
* Check for internal_storage only once (`Process.pid` is slow on Linux)
* Lookup file position only once
TLDR; Speed up counter and histogram by ~6-7%.
```
Warming up --------------------------------------
counter perf-inc    22.380k i/100ms
Calculating -------------------------------------
counter perf-inc    224.104k (± 0.8%) i/s -      1.141M in   5.093434s
Comparison:
counter perf-inc:   224103.9 i/s
counter main:   212032.1 i/s - 1.06x  slower
Warming up --------------------------------------
gauge perf-inc    29.079k i/100ms
Calculating -------------------------------------
gauge perf-inc    289.211k (± 1.8%) i/s -      1.454M in   5.029133s
Comparison:
gauge main:   292329.3 i/s
gauge perf-inc:   289210.9 i/s - same-ish: difference falls …
```
> Optimize incrementing values in DirectFileStore adapter

- spec/prometheus/middleware/exporter_spec.rb
Use `headers` in place of deprecated `header` in tests per https://www.rubydoc.info/gems/rack/Rack%2FResponse:header
Closes #278
> Use Rack::Response#headers in place of header

- lib/prometheus/client/push.rb
- spec/prometheus/client/push_spec.rb
This a subtlety I missed when overhauling the Pushgateway client.
While the job name can't be empty like other grouping key labels can, it can contain `/`, which means we need to base64 encode the value in that case.
> Handle `/` in job name in `Prometheus::Client::Push`

- CHANGELOG.md
- lib/prometheus/client/push.rb
- spec/prometheus/client/push_spec.rb
We do this to all other label values in the client and we should make this one consistent. Right now it's particularly surprising that passing a symbol as the job name results in an error like:
```
undefined method `include?' for :foo:Symbol (NoMethodError)
```
Fixes #295
> Stringify non-string job names in push client

- CHANGELOG.md
- lib/prometheus/client/push.rb
- spec/prometheus/client/push_spec.rb
About a day after fixing this for the job name I realised that I'd made the same mistake a whole ten lines of code further down the method.
---
Relates to #295, #296
> Stringify grouping key values in push client

- .circleci/config.yml
The Ruby version targeted by JRuby 9.3 is now too old for Rubygems to run. Let's pin to the last version that works for now.
When we next have a major version bump for one of the breaking changes we're planning to make (likely around the store interface), we'll clear out support for any Ruby versions that have fallen out of security support.
> Fix JRuby 9.3 build

- .circleci/config.yml
Merry Christmas! 🎄☃️
---
No image from CircleCI just yet, but I'll re-run the tests when it appears. The JRuby 9.3 failure looks like drift and I'll fix it in a separate PR.
> Add Ruby 3.3

- .circleci/config.yml
We've had to switch to the main JRuby Docker image as CircleCI have stopped publishing their own CI-optimised ones with extra tools installed. It turns out this isn't a problem for us as we're not dependent on much in the image.
See: https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
This commit also switches versions 9.2 and 9.3 to the main JRuby Docker image, but not 9.1 as that breaks for some inscrutable reason. We'll drop 9.1 and all other unsupported Rubies in our next major release.
> Add JRuby 9.4 to build matrix

- prometheus-client.gemspec
The base64 gem is [no longer a default gem](https://docs.ruby-lang.org/en/master/NEWS_md.html#label-Stdlib+updates) in Ruby 3.4.
Add base64 to the gemspec, for forward compatibility with Ruby 3.4 and to resolve the `base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0` warning that Ruby 3.3 emits on loading client_ruby.
> Declare base64 gem dependency, ready for Ruby 3.4.

- Gemfile
I was trying to fix CI by pinning `term-ansicolor` to a specific version, but Daniel pointed out that we don't even seem to use it anywhere, so let's throw it (and its `tins` dependency) out.
> Yeet `term-ansicolor` and `tins` from test dependencies

- lib/prometheus/client/histogram.rb
I noticed that we can use binary search as we always have sorted buckets array to improve performance
```shell
ruby 3.3.5 (2024-09-03 revision ef084cc8f4) +YJIT [arm64-darwin23]
Warming up --------------------------------------
default_buckets old   117.753k i/100ms
default_buckets bsearch
226.654k i/100ms
large_buckets old    10.103k i/100ms
large_buckets bsearch
130.281k i/100ms
Calculating -------------------------------------
default_buckets old      1.396M (± 2.8%) i/s  (716.41 ns/i) -      7.065M in   5.065606s
default_buckets bsearch
2.414M (± 5.6%) i/s  (414.22 ns/i) -     12.239M in   5.088910s
large_buckets old     99.015k (± 4.8%) i/s   (10.10 μs/i) -    495.047k in   5.013659s
large_buckets bsearch
1.486M (± 3.2%) i/s  (672.98 ns/i) -      7.426M in   5.003273s
```
With …
> Use binary search for histogram buckets

- lib/prometheus/middleware/collector.rb
- prometheus-client.gemspec
- spec/prometheus/middleware/collector_spec.rb
The benchmark gem is no longer a default gem in Ruby 3.5.
Add benchmark to the gemspec, for forward compatibility with Ruby 3.5 and to resolve the `benchmark was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.' warning that Ruby 3.4 emits on loading client_ruby.
https://docs.ruby-lang.org/en/master/NEWS_md.html#label-Stdlib+updates
> Do not use benchmark gem in production
